apiVersion: v1
kind: ConfigMap
metadata:
  name: truenas-monitor-config
  namespace: truenas-monitor
  labels:
    app.kubernetes.io/name: truenas-monitor
    app.kubernetes.io/component: config
data:
  config.yaml: |
    kubernetes:
      in_cluster: true
      namespace: democratic-csi

    truenas:
      url: ${TRUENAS_URL}
      username: ${TRUENAS_USERNAME}
      password: ${TRUENAS_PASSWORD}
      timeout: 30s

    monitor:
      scan_interval: 5m
      orphan_threshold: 24h
      snapshot_retention: 720h  # 30 days

    metrics:
      enabled: true
      port: 8080
      path: /metrics

    alerts:
      slack:
        webhook: ${SLACK_WEBHOOK}
        channel: "#storage-alerts"