apiVersion: v1
kind: ServiceAccount
metadata:
  name: truenas-monitor
  namespace: truenas-monitor
  labels:
    app.kubernetes.io/name: truenas-monitor
    app.kubernetes.io/component: serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: truenas-monitor
  labels:
    app.kubernetes.io/name: truenas-monitor
    app.kubernetes.io/component: rbac
rules:
# Core resources
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

# Storage resources
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "volumeattachments"]
  verbs: ["get", "list", "watch"]

# CSI resources
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes", "csidrivers"]
  verbs: ["get", "list"]

# Snapshot resources
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontents", "volumesnapshotclasses"]
  verbs: ["get", "list", "watch"]

# Metrics
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: truenas-monitor
  labels:
    app.kubernetes.io/name: truenas-monitor
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: truenas-monitor
subjects:
- kind: ServiceAccount
  name: truenas-monitor
  namespace: truenas-monitor