apiVersion: v1
kind: Secret
metadata:
  name: truenas-credentials
  namespace: truenas-monitor
type: Opaque
stringData:
  password: "changeme"  # Replace with actual password
  api_key: ""           # Optional: API key instead of password