apiVersion: v1
kind: Secret
metadata:
  name: truenas-monitor-secrets
  namespace: truenas-monitor
  labels:
    app.kubernetes.io/name: truenas-monitor
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # TrueNAS credentials - replace with actual values
  TRUENAS_URL: "https://truenas.example.com"
  TRUENAS_USERNAME: "admin"
  TRUENAS_PASSWORD: "changeme"
  
  # Optional: Slack webhook for notifications
  SLACK_WEBHOOK: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"