apiVersion: v1
kind: Service
metadata:
  name: truenas-api-server
  namespace: truenas-monitor
  labels:
    app: truenas-api-server
    component: api-server
spec:
  selector:
    app: truenas-api-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: truenas-monitor-metrics
  namespace: truenas-monitor
  labels:
    app: truenas-monitor
    component: monitor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: truenas-monitor
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP