apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas-monitor
  namespace: truenas-monitor
  labels:
    app: truenas-monitor
    component: monitor
spec:
  selector:
    matchLabels:
      app: truenas-monitor
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s